#!/usr/bin/env python3

"""Plot the two-indicator scaling study generated by `indicator_study`.

Command-line usage:
    python3 plot_indicator_study.py OUTPUT_DIR [--scale-b FLOAT]

Inputs:
    OUTPUT_DIR/indicator_fields.csv, OUTPUT_DIR/marking_history.csv, and the
    AFEPack mesh files written by `run.sh`.
Outputs:
    OUTPUT_DIR/figures/01_indicator_scaling.png,
    02_refinement_comparison.png, and 03_marking_allocation.png.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.collections import LineCollection, PolyCollection


COLORS = {
    "A": "#2f6b9a",
    "B": "#2a9d8f",
    "equal": "#7768ae",
    "scaled": "#d95d4f",
    "mesh": "#294f70",
}


def read_indicator_fields(
    filename: Path,
) -> tuple[list[list[tuple[float, float]]], dict[str, np.ndarray]]:
    polygons: list[list[tuple[float, float]]] = []
    values: dict[str, list[float]] = {
        "eta_a": [],
        "eta_b": [],
        "eta_equal": [],
        "eta_scaled": [],
    }
    with filename.open(newline="") as stream:
        for row in csv.DictReader(stream):
            polygons.append(
                [
                    (float(row["x0"]), float(row["y0"])),
                    (float(row["x1"]), float(row["y1"])),
                    (float(row["x2"]), float(row["y2"])),
                ]
            )
            for key in values:
                values[key].append(float(row[key]))
    return polygons, {key: np.asarray(data) for key, data in values.items()}


def read_nodes(filename: Path) -> list[tuple[float, float]]:
    with filename.open() as stream:
        node_count = int(next(stream).split()[0])
        return [
            (float(fields[1]), float(fields[2]))
            for fields in (
                next(stream).split() for _ in range(node_count)
            )
        ]


def read_elements(filename: Path) -> list[tuple[int, int, int]]:
    with filename.open() as stream:
        element_count = int(next(stream).split()[0])
        return [
            (int(fields[1]), int(fields[2]), int(fields[3]))
            for fields in (
                next(stream).split() for _ in range(element_count)
            )
        ]


def mesh_segments(basename: Path) -> tuple[list[list[tuple[float, float]]], int, int]:
    nodes = read_nodes(basename.with_suffix(".n"))
    elements = read_elements(basename.with_suffix(".e"))
    edges: set[tuple[int, int]] = set()
    for a, b, c in elements:
        edges.update(
            {
                (min(a, b), max(a, b)),
                (min(b, c), max(b, c)),
                (min(c, a), max(c, a)),
            }
        )
    return [[nodes[a], nodes[b]] for a, b in edges], len(nodes), len(elements)


def format_mesh_axis(axis: plt.Axes) -> None:
    axis.set_xlim(-0.015, 1.015)
    axis.set_ylim(-0.015, 1.015)
    axis.set_aspect("equal", adjustable="box")
    axis.set_xticks([])
    axis.set_yticks([])
    for spine in axis.spines.values():
        spine.set_visible(False)


def plot_indicator_fields(
    output_dir: Path,
    figure_dir: Path,
    scale_b: float,
) -> None:
    polygons, values = read_indicator_fields(output_dir / "indicator_fields.csv")
    panels = (
        ("eta_a", r"$\eta_A(K)$", 0.0, 1.0),
        ("eta_b", r"$\eta_B(K)$", 0.0, 1.0),
        ("eta_equal", r"$\eta_A(K)+\eta_B(K)$", 0.0, 1.0),
        (
            "eta_scaled",
            rf"$\eta_A(K)+{scale_b:g}\,\eta_B(K)$",
            0.0,
            scale_b,
        ),
    )
    figure, axes = plt.subplots(1, 4, figsize=(15.2, 3.8))
    for axis, (key, title, lower, upper) in zip(axes, panels):
        collection = PolyCollection(
            polygons,
            array=values[key],
            cmap="YlOrRd",
            clim=(lower, upper),
            edgecolors="#5c7894",
            linewidths=0.18,
        )
        axis.add_collection(collection)
        format_mesh_axis(axis)
        axis.set_title(title, fontsize=15, fontweight="bold", pad=8)
        colorbar = figure.colorbar(collection, ax=axis, fraction=0.046, pad=0.025)
        colorbar.ax.tick_params(labelsize=10)
    figure.tight_layout(pad=0.8)
    figure.savefig(
        figure_dir / "01_indicator_scaling.png",
        dpi=260,
        facecolor="white",
        bbox_inches="tight",
    )
    plt.close(figure)


def plot_final_meshes(
    output_dir: Path,
    figure_dir: Path,
    scale_b: float,
) -> None:
    panels = (
        ("D_refine_lower_left", "Independent A", COLORS["A"]),
        ("D_refine_upper_right", "Independent B", COLORS["B"]),
        ("D_combined_equal", r"Single mesh: $\eta_A+\eta_B$", COLORS["equal"]),
        (
            "D_combined_scaled",
            rf"Single mesh: $\eta_A+{scale_b:g}\eta_B$",
            COLORS["scaled"],
        ),
    )
    figure, axes = plt.subplots(2, 2, figsize=(8.4, 8.4))
    for axis, (name, title, color) in zip(axes.flat, panels):
        segments, node_count, element_count = mesh_segments(output_dir / name)
        axis.add_collection(
            LineCollection(
                segments,
                colors=color,
                linewidths=0.42,
                rasterized=True,
            )
        )
        axis.scatter(
            [0.18, 0.82],
            [0.20, 0.76],
            s=34,
            c=[COLORS["A"], COLORS["B"]],
            edgecolors="white",
            linewidths=0.8,
            zorder=5,
        )
        format_mesh_axis(axis)
        axis.set_title(title, fontsize=15, fontweight="bold", pad=5)
        axis.text(
            0.5,
            -0.055,
            f"{node_count:,} nodes; {element_count:,} EasyMesh triangles",
            transform=axis.transAxes,
            ha="center",
            va="top",
            fontsize=10.5,
            color="#24313d",
        )
    figure.subplots_adjust(
        left=0.025,
        right=0.985,
        bottom=0.045,
        top=0.95,
        wspace=0.08,
        hspace=0.17,
    )
    figure.savefig(
        figure_dir / "02_refinement_comparison.png",
        dpi=300,
        facecolor="white",
        bbox_inches="tight",
    )
    plt.close(figure)


def plot_marking_allocation(output_dir: Path, figure_dir: Path) -> None:
    totals: dict[str, list[int]] = {}
    with (output_dir / "marking_history.csv").open(newline="") as stream:
        for row in csv.DictReader(stream):
            aggregate = totals.setdefault(row["case"], [0, 0])
            aggregate[0] += int(row["marked_near_a"])
            aggregate[1] += int(row["marked_near_b"])

    keys = ("independent_A", "independent_B", "equal_sum", "scaled_sum")
    labels = ("Independent A", "Independent B", "Equal sum", "Scaled sum")
    a_share = np.asarray(
        [100.0 * totals[key][0] / sum(totals[key]) for key in keys]
    )
    b_share = 100.0 - a_share
    positions = np.arange(len(keys))

    figure, axis = plt.subplots(figsize=(8.8, 4.4))
    axis.bar(positions, a_share, color=COLORS["A"], width=0.64, label="near A")
    axis.bar(
        positions,
        b_share,
        bottom=a_share,
        color=COLORS["B"],
        width=0.64,
        label="near B",
    )
    for index, (share_a, share_b) in enumerate(zip(a_share, b_share)):
        if share_a >= 7.0:
            axis.text(
                index,
                share_a / 2.0,
                f"{share_a:.0f}%",
                ha="center",
                va="center",
                color="white",
                fontsize=12,
                fontweight="bold",
            )
        if share_b >= 7.0:
            axis.text(
                index,
                share_a + share_b / 2.0,
                f"{share_b:.0f}%",
                ha="center",
                va="center",
                color="white",
                fontsize=12,
                fontweight="bold",
            )
    axis.set_ylim(0.0, 100.0)
    axis.set_ylabel("share of marked elements", fontsize=13)
    axis.set_xticks(positions, labels, fontsize=11)
    axis.grid(axis="y", color="#d8dee6", linewidth=0.8)
    axis.set_axisbelow(True)
    axis.spines[["top", "right"]].set_visible(False)
    axis.legend(frameon=False, ncols=2, loc="upper center", fontsize=11)
    axis.set_title(
        "A scale coefficient can consume the entire shared marking budget",
        fontsize=15,
        fontweight="bold",
        pad=12,
    )
    figure.tight_layout()
    figure.savefig(
        figure_dir / "03_marking_allocation.png",
        dpi=260,
        facecolor="white",
        bbox_inches="tight",
    )
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--scale-b", type=float, default=50.0)
    arguments = parser.parse_args()
    figure_dir = arguments.output_dir / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    plot_indicator_fields(arguments.output_dir, figure_dir, arguments.scale_b)
    plot_final_meshes(arguments.output_dir, figure_dir, arguments.scale_b)
    plot_marking_allocation(arguments.output_dir, figure_dir)
    print(f"Figures are in {figure_dir}")


if __name__ == "__main__":
    main()
